# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/32db919ab4597f4a6997c7589ac0d676c80043cf124186181f3da47bf60af384.tar.gz";
  hash = "sha256-2EVapA2zVzc6e4tY5S/WJqREBSSqzEUVsWlwQEt9Xzk=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "x64/Diablo III64.exe"; "hash" = "sha256-nT3GvItXt7cf32CLVp2M8ZbUzvLBQp9rX8lYfYsLfgw="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-Moqk+G8M+9alO2F9MPFQUjSbt158roTwx6FLxTBs+1k="; "key" = "e34fc3fb7831a77e0ad7def0bb399ac7"; "url" = "https://level3.ssl.blizzard.com/tpr/diablo3/config/e3/4f/e34fc3fb7831a77e0ad7def0bb399ac7"; }; "buildId" = "99920"; "cdnConfig" = { "hash" = "sha256-RRbvtpik6j0V9ZEx+kQ64vpmMxSyM4w797xDm1DyNxU="; "key" = "6547fc64ca796c7c1b25864145814ace"; "url" = "https://level3.ssl.blizzard.com/tpr/diablo3/config/65/47/6547fc64ca796c7c1b25864145814ace"; }; "cdnPath" = "tpr/diablo3"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "d3"; "productConfig" = "5f66c90e467bd8e8fb5f9b625db233dd"; "region" = "us"; "schemaVersion" = 1; "version" = "2.8.0.99920"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"enUS" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "x64/Diablo III64.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"enUS" ]; }; }; "release" = { "buildConfig" = { "hash" = "sha256-Moqk+G8M+9alO2F9MPFQUjSbt158roTwx6FLxTBs+1k="; "key" = "e34fc3fb7831a77e0ad7def0bb399ac7"; "url" = "https://level3.ssl.blizzard.com/tpr/diablo3/config/e3/4f/e34fc3fb7831a77e0ad7def0bb399ac7"; }; "buildId" = "99920"; "cdnConfig" = { "hash" = "sha256-RRbvtpik6j0V9ZEx+kQ64vpmMxSyM4w797xDm1DyNxU="; "key" = "6547fc64ca796c7c1b25864145814ace"; "url" = "https://level3.ssl.blizzard.com/tpr/diablo3/config/65/47/6547fc64ca796c7c1b25864145814ace"; }; "cdnPath" = "tpr/diablo3"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "d3"; "productConfig" = "5f66c90e467bd8e8fb5f9b625db233dd"; "region" = "us"; "schemaVersion" = 1; "version" = "2.8.0.99920"; }; };
}