# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/65641e1e9a7986af69a6974da798734a9eb4072a480ed41635d37bd3c7338acb.tar.gz";
  hash = "sha256-3841J3ZjZOxLEDJwcoZXvoVm/QjXq4xAPYbEO74L6vA=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "Hearthstone.exe"; "hash" = "sha256-e7EP4c1AotweHxFoDTj5FcV15Rkf0P4AhORvtqdmgjM="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-nrqFfkjqD6WSqLbsBZCsIn7O6aUdnxSbmoupf+dzbMc="; "key" = "4cbc04aa2148bc2d4d4ea465f0651426"; "url" = "https://level3.ssl.blizzard.com/tpr/hs/config/4c/bc/4cbc04aa2148bc2d4d4ea465f0651426"; }; "buildId" = "253932"; "cdnConfig" = { "hash" = "sha256-wxq9bznCefzD3LaqRklAbuM8vqekMUymxBnwiET+yXg="; "key" = "ac123f9a616e3bc31ee1ed5d136ff6f1"; "url" = "https://level3.ssl.blizzard.com/tpr/hs/config/ac/12/ac123f9a616e3bc31ee1ed5d136ff6f1"; }; "cdnPath" = "tpr/hs"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "hsb"; "productConfig" = "1865ee2775377f01668054015d53b9b9"; "region" = "us"; "schemaVersion" = 1; "version" = "36.6.3.253932.253216"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"US"
"Production"
"thTH" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Hearthstone.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"US"
"Production"
"thTH" ]; }; }; "locale" = "thTH"; "productConfiguration" = { "hash" = "sha256-QCMOpvWLmm8iJFUfKWtjuIGdfSGqs/eaPFyi6a10LU0="; "key" = "1865ee2775377f01668054015d53b9b9"; "url" = "https://level3.ssl.blizzard.com/tpr/configs/data/18/65/1865ee2775377f01668054015d53b9b9"; }; "release" = { "buildConfig" = { "hash" = "sha256-nrqFfkjqD6WSqLbsBZCsIn7O6aUdnxSbmoupf+dzbMc="; "key" = "4cbc04aa2148bc2d4d4ea465f0651426"; "url" = "https://level3.ssl.blizzard.com/tpr/hs/config/4c/bc/4cbc04aa2148bc2d4d4ea465f0651426"; }; "buildId" = "253932"; "cdnConfig" = { "hash" = "sha256-wxq9bznCefzD3LaqRklAbuM8vqekMUymxBnwiET+yXg="; "key" = "ac123f9a616e3bc31ee1ed5d136ff6f1"; "url" = "https://level3.ssl.blizzard.com/tpr/hs/config/ac/12/ac123f9a616e3bc31ee1ed5d136ff6f1"; }; "cdnPath" = "tpr/hs"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "hsb"; "productConfig" = "1865ee2775377f01668054015d53b9b9"; "region" = "us"; "schemaVersion" = 1; "version" = "36.6.3.253932.253216"; }; };
}