# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/42a934cc729a948903efa236e71511e675ecf9d12549768f445e2d36ccb8ed7f.tar.gz";
  hash = "sha256-ChcrDG2VZtRX1oUewH/Aee6OOdiGqpzmbb0cql2kFOQ=";
  game = { "installation" = { "args" = [  ]; "executable" = "D2R.exe"; "hash" = "sha256-z5tM3QgGR2QVTlJgKRugEiv2XMLs6K803VvpSU9gE+k="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-z92x/1Wkp7PxzmjRO84RTZfhE0mPpdxEWfbBLIV2oqA="; "key" = "623f7a1f73eabb08ccb2b2046e3f9164"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/62/3f/623f7a1f73eabb08ccb2b2046e3f9164"; }; "buildId" = "93847"; "cdnConfig" = { "hash" = "sha256-ZwX1mUbYZz4bknUnnz4236Gs0dAiYdB4Hr1edXwbTAo="; "key" = "a10f39cd385730caa4ab1909c888a845"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/a1/0f/a10f39cd385730caa4ab1909c888a845"; }; "cdnPath" = "tpr/osi"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "osi"; "productConfig" = "e5d0a3feb55588a5da2ede452171d0fc"; "region" = "us"; "schemaVersion" = 1; "version" = "3.3.93847"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"enUS" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "D2R.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"x86_64"
"enUS" ]; }; }; "release" = { "buildConfig" = { "hash" = "sha256-z92x/1Wkp7PxzmjRO84RTZfhE0mPpdxEWfbBLIV2oqA="; "key" = "623f7a1f73eabb08ccb2b2046e3f9164"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/62/3f/623f7a1f73eabb08ccb2b2046e3f9164"; }; "buildId" = "93847"; "cdnConfig" = { "hash" = "sha256-ZwX1mUbYZz4bknUnnz4236Gs0dAiYdB4Hr1edXwbTAo="; "key" = "a10f39cd385730caa4ab1909c888a845"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/a1/0f/a10f39cd385730caa4ab1909c888a845"; }; "cdnPath" = "tpr/osi"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "osi"; "productConfig" = "e5d0a3feb55588a5da2ede452171d0fc"; "region" = "us"; "schemaVersion" = 1; "version" = "3.3.93847"; }; };
}