# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/50cdc04c5655011fd5820aab2cb5c3e726ae48513f086858e2674dc283dee7d8.tar.gz";
  hash = "sha256-Smeki09cueZM/FP9f9NONUGirbOql030lJq5egVTxVI=";
  game = { "installation" = { "args" = [  ]; "executable" = "D2R.exe"; "hash" = "sha256-fqHgov67gn70O3AQJR3euFmw/sPbZHd9kx9Ja6auKoQ="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-z92x/1Wkp7PxzmjRO84RTZfhE0mPpdxEWfbBLIV2oqA="; "key" = "623f7a1f73eabb08ccb2b2046e3f9164"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/62/3f/623f7a1f73eabb08ccb2b2046e3f9164"; }; "buildId" = "93847"; "cdnConfig" = { "hash" = "sha256-ZwX1mUbYZz4bknUnnz4236Gs0dAiYdB4Hr1edXwbTAo="; "key" = "a10f39cd385730caa4ab1909c888a845"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/a1/0f/a10f39cd385730caa4ab1909c888a845"; }; "cdnPath" = "tpr/osi"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "osi"; "productConfig" = "e5d0a3feb55588a5da2ede452171d0fc"; "region" = "us"; "schemaVersion" = 1; "version" = "3.3.93847"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"jaJP" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "D2R.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"x86_64"
"jaJP" ]; }; }; "locale" = "jaJP"; "productConfiguration" = { "hash" = "sha256-bZlb6xUqKKk5XSMH+mTLMCXLD+wKJk0n4QK6KnJdCGc="; "key" = "e5d0a3feb55588a5da2ede452171d0fc"; "url" = "https://level3.ssl.blizzard.com/tpr/configs/data/e5/d0/e5d0a3feb55588a5da2ede452171d0fc"; }; "release" = { "buildConfig" = { "hash" = "sha256-z92x/1Wkp7PxzmjRO84RTZfhE0mPpdxEWfbBLIV2oqA="; "key" = "623f7a1f73eabb08ccb2b2046e3f9164"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/62/3f/623f7a1f73eabb08ccb2b2046e3f9164"; }; "buildId" = "93847"; "cdnConfig" = { "hash" = "sha256-ZwX1mUbYZz4bknUnnz4236Gs0dAiYdB4Hr1edXwbTAo="; "key" = "a10f39cd385730caa4ab1909c888a845"; "url" = "https://level3.ssl.blizzard.com/tpr/osi/config/a1/0f/a10f39cd385730caa4ab1909c888a845"; }; "cdnPath" = "tpr/osi"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "osi"; "productConfig" = "e5d0a3feb55588a5da2ede452171d0fc"; "region" = "us"; "schemaVersion" = 1; "version" = "3.3.93847"; }; };
}