# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/869045ca3352310f0b80b46295e2495d11d91e8bd86f8a732997c839a37796d4.tar.gz";
  hash = "sha256-hL8C2RPNHVoqS0NCtcPIGZBzZREGHEH9F3iUkHYkqvo=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "x86_64/StarCraft.exe"; "hash" = "sha256-lyiS5h4aVwwUrB1o42HSwWXHlwEsZMN8UUx2YFAe4wE="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-ckoNqMF58myKbMwbQJeOrpLQh9Y8A1VA47io4vwCrdg="; "key" = "864772b9ff94f6d372aa4ee90ee2f8ab"; "url" = "https://level3.ssl.blizzard.com/tpr/sc1live/config/86/47/864772b9ff94f6d372aa4ee90ee2f8ab"; }; "buildId" = "13515"; "cdnConfig" = { "hash" = "sha256-mcvjavj/mlp7WkpX18yMRqkP4w8C5gYxs45uwYmuGbg="; "key" = "bd4a0f876fdbf39666f0fae661e54974"; "url" = "https://level3.ssl.blizzard.com/tpr/sc1live/config/bd/4a/bd4a0f876fdbf39666f0fae661e54974"; }; "cdnPath" = "tpr/sc1live"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s1"; "productConfig" = "c61fc45c039ea8dfd98febbc5b6e73b8"; "region" = "us"; "schemaVersion" = 1; "version" = "1.23.10.13515"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"Release"
"noigr"
"koKR" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "x86_64/StarCraft.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"x86_64"
"Release"
"noigr"
"koKR" ]; }; }; "locale" = "koKR"; "productConfiguration" = { "hash" = "sha256-MalNjpjXz51cWUXHA8L2MR6wCPXHnt7y4iSpacBwPBo="; "key" = "c61fc45c039ea8dfd98febbc5b6e73b8"; "url" = "https://level3.ssl.blizzard.com/tpr/configs/data/c6/1f/c61fc45c039ea8dfd98febbc5b6e73b8"; }; "release" = { "buildConfig" = { "hash" = "sha256-ckoNqMF58myKbMwbQJeOrpLQh9Y8A1VA47io4vwCrdg="; "key" = "864772b9ff94f6d372aa4ee90ee2f8ab"; "url" = "https://level3.ssl.blizzard.com/tpr/sc1live/config/86/47/864772b9ff94f6d372aa4ee90ee2f8ab"; }; "buildId" = "13515"; "cdnConfig" = { "hash" = "sha256-mcvjavj/mlp7WkpX18yMRqkP4w8C5gYxs45uwYmuGbg="; "key" = "bd4a0f876fdbf39666f0fae661e54974"; "url" = "https://level3.ssl.blizzard.com/tpr/sc1live/config/bd/4a/bd4a0f876fdbf39666f0fae661e54974"; }; "cdnPath" = "tpr/sc1live"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s1"; "productConfig" = "c61fc45c039ea8dfd98febbc5b6e73b8"; "region" = "us"; "schemaVersion" = 1; "version" = "1.23.10.13515"; }; };
}