# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/5438a15e19eb4dd487351bb0e096faac18ddd40e8f0c382439240ce904a164bc.tar.gz";
  hash = "sha256-THLp6zGexN1b2dQpJ6Es5IWkpTmWPLZyurrHV+L9pik=";
  game = { "catalogProduct" = "s2"; "installation" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "hash" = "sha256-PMIjWYiticTaAlz7zpMdd0dvJWRZEX0ZmCmrGauXY7M="; "storage" = { "completeInstallation" = true; "dataDirectory" = "SC2Data"; "release" = { "buildConfig" = { "hash" = "sha256-UMbp4A/4lfEXgHCMl5DJ8irDWGr4lXcCoagHJYlX5N0="; "key" = "8453c2f1c98b955334c7284215429c36"; "url" = "https://blzdist-s2.necdn.leihuo.netease.com/tpr/sc2/config/84/53/8453c2f1c98b955334c7284215429c36"; }; "buildId" = "93333"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://blzdist-s2.necdn.leihuo.netease.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://blzdist-s2.necdn.leihuo.netease.com"
"http://blzdist-s2.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "cn"; "schemaVersion" = 1; "version" = "5.0.14.93333"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"CN"
"speech"
"text"
"zhCN" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "storage" = { "dataDirectory" = "SC2Data"; "tags" = [ "Windows"
"CN"
"speech"
"text"
"zhCN" ]; }; }; "locale" = "zhCN"; "productConfiguration" = { "hash" = "sha256-dCKj0J7gFgoX2WvuJWmtsw7uLT+nsBIjypGxP7hlo+w="; "key" = "0c241b7c4662aa04df68134b5ecdd181"; "url" = "https://blzdist-s2.necdn.leihuo.netease.com/tpr/configs/data/0c/24/0c241b7c4662aa04df68134b5ecdd181"; }; "release" = { "buildConfig" = { "hash" = "sha256-UMbp4A/4lfEXgHCMl5DJ8irDWGr4lXcCoagHJYlX5N0="; "key" = "8453c2f1c98b955334c7284215429c36"; "url" = "https://blzdist-s2.necdn.leihuo.netease.com/tpr/sc2/config/84/53/8453c2f1c98b955334c7284215429c36"; }; "buildId" = "93333"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://blzdist-s2.necdn.leihuo.netease.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://blzdist-s2.necdn.leihuo.netease.com"
"http://blzdist-s2.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "cn"; "schemaVersion" = 1; "version" = "5.0.14.93333"; }; "serviceRegion" = "cn"; };
}