# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/7aae718ab4f3926766da94c7b3d297b4614dd237eddfd2b50a2f519c522a730a.tar.gz";
  hash = "sha256-xz2oGbR6faa29yceDW6xaBHbyQdzfxm0+VNpfMsDim8=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "SC2Data"; "release" = { "buildConfig" = { "hash" = "sha256-PyWTcsrM6/wqwEwuazX640nDDol7X2QH6uoBF48e0D8="; "key" = "1d231af579faf03e61a364722a3b87b4"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/1d/23/1d231af579faf03e61a364722a3b87b4"; }; "buildId" = "98310"; "cdnConfig" = { "hash" = "sha256-KHMSqfvBh5MGfhDg+Vw1R5lKiGXmvOd/K49/HQDPG+k="; "key" = "e4f2e2da310c08495f2701d401d14659"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/e4/f2/e4f2e2da310c08495f2701d401d14659"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.17.98310"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"US"
"speech"
"text"
"frFR" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "storage" = { "dataDirectory" = "SC2Data"; "tags" = [ "Windows"
"US"
"speech"
"text"
"frFR" ]; }; }; "locale" = "frFR"; "productConfiguration" = { "hash" = "sha256-dCKj0J7gFgoX2WvuJWmtsw7uLT+nsBIjypGxP7hlo+w="; "key" = "0c241b7c4662aa04df68134b5ecdd181"; "url" = "https://level3.ssl.blizzard.com/tpr/configs/data/0c/24/0c241b7c4662aa04df68134b5ecdd181"; }; "release" = { "buildConfig" = { "hash" = "sha256-PyWTcsrM6/wqwEwuazX640nDDol7X2QH6uoBF48e0D8="; "key" = "1d231af579faf03e61a364722a3b87b4"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/1d/23/1d231af579faf03e61a364722a3b87b4"; }; "buildId" = "98310"; "cdnConfig" = { "hash" = "sha256-KHMSqfvBh5MGfhDg+Vw1R5lKiGXmvOd/K49/HQDPG+k="; "key" = "e4f2e2da310c08495f2701d401d14659"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/e4/f2/e4f2e2da310c08495f2701d401d14659"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.17.98310"; }; };
}