# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/79b06a1afe92ba2f5a3696e327651d8124fe969342e1738a7876951d1d0443cf.tar.gz";
  hash = "sha256-cMLtD2nJ5StlIlM4ZD558wOta2SgAPigtohb+2d3dlY=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "hash" = "sha256-db++yP+1RpN3psQHSPhhHbh1IwFIq99NswqUCpEombc="; "storage" = { "completeInstallation" = true; "dataDirectory" = "SC2Data"; "release" = { "buildConfig" = { "hash" = "sha256-27R6cHcpJEP8Th9D3heAt9YFe98hQAHzmKWXEq4Tsg4="; "key" = "5bc8dcc1fade3a320c12936586b7c0ed"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/5b/c8/5bc8dcc1fade3a320c12936586b7c0ed"; }; "buildId" = "97563"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.16.97563"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"US"
"speech"
"text"
"itIT" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "storage" = { "dataDirectory" = "SC2Data"; "tags" = [ "Windows"
"US"
"speech"
"text"
"itIT" ]; }; }; "locale" = "itIT"; "productConfiguration" = { "hash" = "sha256-dCKj0J7gFgoX2WvuJWmtsw7uLT+nsBIjypGxP7hlo+w="; "key" = "0c241b7c4662aa04df68134b5ecdd181"; "url" = "https://cdn.blizzard.com/tpr/configs/data/0c/24/0c241b7c4662aa04df68134b5ecdd181"; }; "release" = { "buildConfig" = { "hash" = "sha256-27R6cHcpJEP8Th9D3heAt9YFe98hQAHzmKWXEq4Tsg4="; "key" = "5bc8dcc1fade3a320c12936586b7c0ed"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/5b/c8/5bc8dcc1fade3a320c12936586b7c0ed"; }; "buildId" = "97563"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.16.97563"; }; };
}