# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/ae3d71a6900706c4ae38bf8c45bd3f95ad07760cf27f86f864a36bbb47f07c96.tar.gz";
  hash = "sha256-GrcnG5KcHsie4Fo7OXrzMpoSs+s3iadJ1CoOssVJPmc=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "SC2Data"; "release" = { "buildConfig" = { "hash" = "sha256-PyWTcsrM6/wqwEwuazX640nDDol7X2QH6uoBF48e0D8="; "key" = "1d231af579faf03e61a364722a3b87b4"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/1d/23/1d231af579faf03e61a364722a3b87b4"; }; "buildId" = "98310"; "cdnConfig" = { "hash" = "sha256-KHMSqfvBh5MGfhDg+Vw1R5lKiGXmvOd/K49/HQDPG+k="; "key" = "e4f2e2da310c08495f2701d401d14659"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/e4/f2/e4f2e2da310c08495f2701d401d14659"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.17.98310"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"enUS"
"US"
"speech"
"text" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "storage" = { "dataDirectory" = "SC2Data"; "tags" = [ "Windows"
"enUS"
"US"
"speech"
"text" ]; }; }; "release" = { "buildConfig" = { "hash" = "sha256-PyWTcsrM6/wqwEwuazX640nDDol7X2QH6uoBF48e0D8="; "key" = "1d231af579faf03e61a364722a3b87b4"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/1d/23/1d231af579faf03e61a364722a3b87b4"; }; "buildId" = "98310"; "cdnConfig" = { "hash" = "sha256-KHMSqfvBh5MGfhDg+Vw1R5lKiGXmvOd/K49/HQDPG+k="; "key" = "e4f2e2da310c08495f2701d401d14659"; "url" = "https://cdn.blizzard.com/tpr/sc2/config/e4/f2/e4f2e2da310c08495f2701d401d14659"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.17.98310"; }; };
}