# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/361d44218364442de0e4fdd5557042918f367717bd0f8b89d2daec1d2695b8c0.tar.gz";
  hash = "sha256-+EE5KkL7bF+CGZjnJE+tbY4tL1yAu8Q7/NWketEJ66A=";
  game = { "installation" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "hash" = "sha256-mibu0MheVUnjphk9MY8XrZL46KO5XSHxiKqTf12H5EE="; "storage" = { "completeInstallation" = true; "dataDirectory" = "SC2Data"; "release" = { "buildConfig" = { "hash" = "sha256-27R6cHcpJEP8Th9D3heAt9YFe98hQAHzmKWXEq4Tsg4="; "key" = "5bc8dcc1fade3a320c12936586b7c0ed"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/5b/c8/5bc8dcc1fade3a320c12936586b7c0ed"; }; "buildId" = "97563"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.16.97563"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"enUS"
"US"
"speech"
"text" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch" ]; "executable" = "Support64/SC2Switcher_x64.exe"; "storage" = { "dataDirectory" = "SC2Data"; "tags" = [ "Windows"
"enUS"
"US"
"speech"
"text" ]; }; }; "release" = { "buildConfig" = { "hash" = "sha256-27R6cHcpJEP8Th9D3heAt9YFe98hQAHzmKWXEq4Tsg4="; "key" = "5bc8dcc1fade3a320c12936586b7c0ed"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/5b/c8/5bc8dcc1fade3a320c12936586b7c0ed"; }; "buildId" = "97563"; "cdnConfig" = { "hash" = "sha256-gyJYuJtweMgNqOlwPp+BnSZ++XNobz5cSwE2VJWiB50="; "key" = "85dc7fd5646db6c1c0425dd814d7409e"; "url" = "https://level3.ssl.blizzard.com/tpr/sc2/config/85/dc/85dc7fd5646db6c1c0425dd814d7409e"; }; "cdnPath" = "tpr/sc2"; "cdnServers" = [ "https://level3.ssl.blizzard.com"
"https://us.cdn.blizzard.com"
"http://level3.blizzard.com"
"http://us.cdn.blizzard.com" ]; "keyRing" = ""; "product" = "s2"; "productConfig" = "0c241b7c4662aa04df68134b5ecdd181"; "region" = "us"; "schemaVersion" = 1; "version" = "5.0.16.97563"; }; };
}