# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/93a4479ec6369dacf3f19096d672be74bf84d7b60426f7a923b0876021b931f5.tar.gz";
  hash = "sha256-4QfubGUpILJnkoACpgK0QeAi+BqVOlX16T+8O5/KxFA=";
  game = { "installation" = { "args" = [ "-launch"
"-locale"
"esES" ]; "executable" = "x86_64/Warcraft III.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://cdn.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-wP5XAtkssv0odxENA+0o+ekRNsRt2n5vBhnuBdZHbpA="; "key" = "a236994e73cdb0dab5971a784cab852e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/a2/36/a236994e73cdb0dab5971a784cab852e"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"Release"
"esES" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch"
"-locale"
"esES" ]; "executable" = "x86_64/Warcraft III.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"Release"
"esES" ]; }; }; "locale" = "esES"; "productConfiguration" = { "hash" = "sha256-ZXGYZvMepR+DYAdeo6vDOcDHDjNM2l67mNa7FAJat2A="; "key" = "f220f1a2d27b38e9469987ff66e61f04"; "url" = "https://cdn.blizzard.com/tpr/configs/data/f2/20/f220f1a2d27b38e9469987ff66e61f04"; }; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://cdn.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-wP5XAtkssv0odxENA+0o+ekRNsRt2n5vBhnuBdZHbpA="; "key" = "a236994e73cdb0dab5971a784cab852e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/a2/36/a236994e73cdb0dab5971a784cab852e"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; };
}