# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet-overlay/releases/download/catalogs/2e72f6d75694c864c7715e119c4c07421e1e54f5a3c24bad16e263d73585f81a.tar.gz";
  hash = "sha256-sIGWdcY7iVQR9nMN+Zh7ir7wOp0H/pdy22fR4kgNF94=";
  game = { "installation" = { "args" = [ "-launch"
"-locale"
"ptBR" ]; "executable" = "x86_64/Warcraft III.exe"; "hash" = "sha256-MSGjyWti04FXg3RkFN3aXFsq0BFeBMf4Buu9gJshvvY="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"Release"
"ptBR" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch"
"-locale"
"ptBR" ]; "executable" = "x86_64/Warcraft III.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"Release"
"ptBR" ]; }; }; "locale" = "ptBR"; "productConfiguration" = { "hash" = "sha256-ZXGYZvMepR+DYAdeo6vDOcDHDjNM2l67mNa7FAJat2A="; "key" = "f220f1a2d27b38e9469987ff66e61f04"; "url" = "https://cdn.blizzard.com/tpr/configs/data/f2/20/f220f1a2d27b38e9469987ff66e61f04"; }; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; };
}