# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet-overlay/releases/download/catalogs/67991b4ab014e027381ed23bff83c6dca3dd8270c9686c7bdbfdcbabf896e466.tar.gz";
  hash = "sha256-pAoeRBtCneA+5jP0eqJwIE4+UQd48oaXy1ro+Uhx4u0=";
  game = { "installation" = { "args" = [ "-launch"
"-locale"
"plPL" ]; "executable" = "x86_64/Warcraft III.exe"; "hash" = "sha256-JuRoir36cQVvBDBk2Po6M06Y8/u6fPJqltbHKRLApJo="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"Release"
"plPL" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch"
"-locale"
"plPL" ]; "executable" = "x86_64/Warcraft III.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"Release"
"plPL" ]; }; }; "locale" = "plPL"; "productConfiguration" = { "hash" = "sha256-ZXGYZvMepR+DYAdeo6vDOcDHDjNM2l67mNa7FAJat2A="; "key" = "f220f1a2d27b38e9469987ff66e61f04"; "url" = "https://cdn.blizzard.com/tpr/configs/data/f2/20/f220f1a2d27b38e9469987ff66e61f04"; }; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; };
}