# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet-overlay/releases/download/catalogs/227605f54e1a3d569bf1fc986033c7fa373f812bde51140f08b935a685d193ce.tar.gz";
  hash = "sha256-CwaVySrnoGNJEzzEHsxm+tvol+qFFwxSg0KPOaW9/54=";
  game = { "installation" = { "args" = [ "-launch"
"-locale"
"zhCN" ]; "executable" = "x86_64/Warcraft III.exe"; "hash" = "sha256-eUKBLIK1U3HqydpMMvfXK5ZhLAQOxFb2hZhWo2TRYps="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"Release"
"zhCN" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch"
"-locale"
"zhCN" ]; "executable" = "x86_64/Warcraft III.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"Release"
"zhCN" ]; }; }; "locale" = "zhCN"; "productConfiguration" = { "hash" = "sha256-ZXGYZvMepR+DYAdeo6vDOcDHDjNM2l67mNa7FAJat2A="; "key" = "f220f1a2d27b38e9469987ff66e61f04"; "url" = "https://cdn.blizzard.com/tpr/configs/data/f2/20/f220f1a2d27b38e9469987ff66e61f04"; }; "release" = { "buildConfig" = { "hash" = "sha256-NaPjKkIMHEq1wZmmegrrD/ksP5MEN8NAzKyuobN3rU4="; "key" = "3a9d8f26806936764d2d9ad526a65e04"; "url" = "https://level3.ssl.blizzard.com/tpr/war3/config/3a/9d/3a9d8f26806936764d2d9ad526a65e04"; }; "buildId" = "24268"; "cdnConfig" = { "hash" = "sha256-5g3SayCcUy8vk/cs1/EkxYruqgk8ReLRQ7qaL88DiHs="; "key" = "f0b3934c08beaca44d58ec2a15865812"; "url" = "https://cdn.blizzard.com/tpr/war3/config/f0/b3/f0b3934c08beaca44d58ec2a15865812"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.0.24268"; }; };
}