# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/80692240f64a1c64239f6c3efe48b22fb5afad7e300ffe4fe824a28e589068b3.tar.gz";
  hash = "sha256-88UHStFKeb0YcER8l57dMGF1IxV71xr/XylHige5/LQ=";
  game = { "installation" = { "args" = [ "-launch"
"-locale"
"zhTW" ]; "executable" = "x86_64/Warcraft III.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "release" = { "buildConfig" = { "hash" = "sha256-D+WE+hW5maLJ5JQwKOQE30wMGMa4yA/dtPy9sW2ZV1k="; "key" = "3e86fe0fe6831523070f73465dcacf9e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/3e/86/3e86fe0fe6831523070f73465dcacf9e"; }; "buildId" = "24342"; "cdnConfig" = { "hash" = "sha256-wP5XAtkssv0odxENA+0o+ekRNsRt2n5vBhnuBdZHbpA="; "key" = "a236994e73cdb0dab5971a784cab852e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/a2/36/a236994e73cdb0dab5971a784cab852e"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.1.24342"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"Release"
"zhTW" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [ "-launch"
"-locale"
"zhTW" ]; "executable" = "x86_64/Warcraft III.exe"; "storage" = { "dataDirectory" = "Data"; "tags" = [ "Windows"
"Release"
"zhTW" ]; }; }; "locale" = "zhTW"; "productConfiguration" = { "hash" = "sha256-ZXGYZvMepR+DYAdeo6vDOcDHDjNM2l67mNa7FAJat2A="; "key" = "f220f1a2d27b38e9469987ff66e61f04"; "url" = "https://cdn.blizzard.com/tpr/configs/data/f2/20/f220f1a2d27b38e9469987ff66e61f04"; }; "release" = { "buildConfig" = { "hash" = "sha256-D+WE+hW5maLJ5JQwKOQE30wMGMa4yA/dtPy9sW2ZV1k="; "key" = "3e86fe0fe6831523070f73465dcacf9e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/3e/86/3e86fe0fe6831523070f73465dcacf9e"; }; "buildId" = "24342"; "cdnConfig" = { "hash" = "sha256-wP5XAtkssv0odxENA+0o+ekRNsRt2n5vBhnuBdZHbpA="; "key" = "a236994e73cdb0dab5971a784cab852e"; "url" = "https://cdn.blizzard.com/tpr/war3/config/a2/36/a236994e73cdb0dab5971a784cab852e"; }; "cdnPath" = "tpr/war3"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "w3"; "productConfig" = "f220f1a2d27b38e9469987ff66e61f04"; "region" = "us"; "schemaVersion" = 1; "version" = "3.0.1.24342"; }; };
}