# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/31f28cb64071388387a1d13413c056f8531acdb8c5054f6ed33b9d8323471e17.tar.gz";
  hash = "sha256-zvxteVzWTM7Ee25Cu/1rEMvXK/0+U/jHzW1uTlUGqxQ=";
  game = { "installation" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "architectures" = [ "arm64"
"x86_64" ]; "args" = [  ]; "executable" = "_classic_era_/World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "hash" = null; "runtime" = "native"; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-/RSWFFmnO1QB16a28Rpz+FHJXtMO0gqo7tviIr5WDdo="; "key" = "00df9e43531518b653a35289488c9bbb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/00/df/00df9e43531518b653a35289488c9bbb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "OSX"
"US"
"speech"
"text"
"deDE"
"arm64" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "args" = [  ]; "executable" = "World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "runtime" = "native"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "OSX"
"US"
"speech"
"text"
"deDE" ]; }; }; "locale" = "deDE"; "platform" = "mac"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://cdn.blizzard.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-/RSWFFmnO1QB16a28Rpz+FHJXtMO0gqo7tviIr5WDdo="; "key" = "00df9e43531518b653a35289488c9bbb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/00/df/00df9e43531518b653a35289488c9bbb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}