# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/1bb84ae07e24d2d8010f82c4592cc96e4644dfc2f8d2d7aea40befe8a06ed8bb.tar.gz";
  hash = "sha256-oYC806Wt9fundP+9sNVY5+hWQgLIUD+c1DMVg+cG+bw=";
  game = { "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-JQuLdJUrTGqwfeuItajhmDKz10EzNZ6h+uHjne6aEK8="; "key" = "26b68e5ddb5ae3011a84c41062da2efb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/26/b6/26b68e5ddb5ae3011a84c41062da2efb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"esMX" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"esMX" ]; }; }; "locale" = "esMX"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://cdn.blizzard.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-JQuLdJUrTGqwfeuItajhmDKz10EzNZ6h+uHjne6aEK8="; "key" = "26b68e5ddb5ae3011a84c41062da2efb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/26/b6/26b68e5ddb5ae3011a84c41062da2efb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}