# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/343909525a29060cfdad3939d8af9811390b47fca2e493aaed9c2a015fb2e6b4.tar.gz";
  hash = "sha256-RoYlgKe+ETmY+Gk4MpjWrZVOvSUmBBH5vXqcO/RaLJM=";
  game = { "catalogProduct" = "wow_classic_era"; "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-/RSWFFmnO1QB16a28Rpz+FHJXtMO0gqo7tviIr5WDdo="; "key" = "00df9e43531518b653a35289488c9bbb"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/00/df/00df9e43531518b653a35289488c9bbb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://blzdist-wow.necdn.leihuo.netease.com"
"http://blzdist-wow.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "cn"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"CN"
"speech"
"text"
"zhCN"
"Alternate" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WoWClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"CN"
"speech"
"text"
"zhCN"
"Alternate" ]; }; }; "locale" = "zhCN"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-/RSWFFmnO1QB16a28Rpz+FHJXtMO0gqo7tviIr5WDdo="; "key" = "00df9e43531518b653a35289488c9bbb"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/00/df/00df9e43531518b653a35289488c9bbb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://blzdist-wow.necdn.leihuo.netease.com"
"http://blzdist-wow.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "cn"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "serviceRegion" = "cn"; };
}