# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet-overlay/releases/download/catalogs/b11e3b5fe1e2d4e77eeaacfcfefb73103342a6d4cea457ba47ba0d16a2880672.tar.gz";
  hash = "sha256-Dn8l3Sk4hEuOz9KF5RT78GYg2GiC3R8FG+WRi8IApeI=";
  game = { "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = "sha256-WtKcFSxcqgBjALfLgmZaqpEcgnzP0dFlY9N36c5myh4="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Q1lv7ZeVeEjsPc8lD6gKOTNVbGWGYArSbtBeQZR4cjc="; "key" = "ce9356750f0c9edb005bb03d8bf37384"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/ce/93/ce9356750f0c9edb005bb03d8bf37384"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"zhTW" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"zhTW" ]; }; }; "locale" = "zhTW"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://cdn.blizzard.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Q1lv7ZeVeEjsPc8lD6gKOTNVbGWGYArSbtBeQZR4cjc="; "key" = "ce9356750f0c9edb005bb03d8bf37384"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/ce/93/ce9356750f0c9edb005bb03d8bf37384"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}