# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/9997afaff83b881e42bf124b1d5bae7749c032b39f7c97cfd02a48828f1337aa.tar.gz";
  hash = "sha256-e6bBVEhamGTSwQxG+RdMgIU3El9epCTeLRn4xN3YJWI=";
  game = { "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = "sha256-uDVU2fC0nJzlYv2fPR7QPF6xcif68WinoKDw+B4RMHk="; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-WPwSQuliv0q3fVYGekFZBJIB2duImwfzVWWntlIu1xw="; "key" = "10cbde32d9c922d6416472d24b7d4801"; "url" = "https://cdn.blizzard.com/tpr/wow/config/10/cb/10cbde32d9c922d6416472d24b7d4801"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"enUS"
"US"
"speech"
"text" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"enUS"
"US"
"speech"
"text" ]; }; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-WPwSQuliv0q3fVYGekFZBJIB2duImwfzVWWntlIu1xw="; "key" = "10cbde32d9c922d6416472d24b7d4801"; "url" = "https://cdn.blizzard.com/tpr/wow/config/10/cb/10cbde32d9c922d6416472d24b7d4801"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}