# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/cc848ca155cf76e11dc2c7659018ca63d71aa0157b56f7979fe5697369d2c117.tar.gz";
  hash = "sha256-M7VLJj3+x8WBAJCO8ftJaDA+bz7ksF6on03LJUz41IA=";
  game = { "catalogProduct" = "wow_classic_era"; "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Azpdv/4zJ0GWTo7ScW2oS+MFlDpjVSoFI6OhSy1+Rfo="; "key" = "ad00f88bc136373cdfe57c6bb796516b"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/ad/00/ad00f88bc136373cdfe57c6bb796516b"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://blzdist-wow.necdn.leihuo.netease.com"
"http://blzdist-wow.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "cn"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"CN"
"speech"
"text"
"zhCN"
"Alternate" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WoWClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"CN"
"speech"
"text"
"zhCN"
"Alternate" ]; }; }; "locale" = "zhCN"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Azpdv/4zJ0GWTo7ScW2oS+MFlDpjVSoFI6OhSy1+Rfo="; "key" = "ad00f88bc136373cdfe57c6bb796516b"; "url" = "https://blzdist-wow.necdn.leihuo.netease.com/tpr/wow/config/ad/00/ad00f88bc136373cdfe57c6bb796516b"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://blzdist-wow.necdn.leihuo.netease.com"
"http://blzdist-wow.necdn.leihuo.netease.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "cn"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "serviceRegion" = "cn"; };
}