# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/097b33ba6817666044ee6b035e00462e9e8526722409580726d2095df1d2cdd1.tar.gz";
  hash = "sha256-GOmdb+Eo1fsUS++q7HNdx9mAoMOvUAijr/21esH8OaE=";
  game = { "installation" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "hash" = null; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-XNQRg1ftFqtXSUkF8rB0jvGJ+aJnzQ4s42S7wQR5BIM="; "key" = "f39eaf0d23ad9a0f85fdbfc2713d3ed3"; "url" = "https://cdn.blizzard.com/tpr/wow/config/f3/9e/f39eaf0d23ad9a0f85fdbfc2713d3ed3"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"zhCN" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "args" = [  ]; "executable" = "_classic_era_/WowClassic.exe"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "Windows"
"x86_64"
"US"
"speech"
"text"
"zhCN" ]; }; }; "locale" = "zhCN"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-XNQRg1ftFqtXSUkF8rB0jvGJ+aJnzQ4s42S7wQR5BIM="; "key" = "f39eaf0d23ad9a0f85fdbfc2713d3ed3"; "url" = "https://cdn.blizzard.com/tpr/wow/config/f3/9e/f39eaf0d23ad9a0f85fdbfc2713d3ed3"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}