# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/12de3e39cce3e2a539900b505fac0125c7629577a1dc4e6bbf3a66a550926ad0.tar.gz";
  hash = "sha256-BoEGWFG+NSAM6dnGNzV9l887hmN75rx9nz1gdcANN4A=";
  game = { "installation" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "architectures" = [ "arm64"
"x86_64" ]; "args" = [  ]; "executable" = "_classic_era_/World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "hash" = null; "runtime" = "native"; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Azpdv/4zJ0GWTo7ScW2oS+MFlDpjVSoFI6OhSy1+Rfo="; "key" = "ad00f88bc136373cdfe57c6bb796516b"; "url" = "https://cdn.blizzard.com/tpr/wow/config/ad/00/ad00f88bc136373cdfe57c6bb796516b"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "OSX"
"US"
"speech"
"text"
"koKR"
"arm64" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "args" = [  ]; "executable" = "World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "runtime" = "native"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "OSX"
"US"
"speech"
"text"
"koKR" ]; }; }; "locale" = "koKR"; "platform" = "mac"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://cdn.blizzard.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-Azpdv/4zJ0GWTo7ScW2oS+MFlDpjVSoFI6OhSy1+Rfo="; "key" = "ad00f88bc136373cdfe57c6bb796516b"; "url" = "https://cdn.blizzard.com/tpr/wow/config/ad/00/ad00f88bc136373cdfe57c6bb796516b"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}