# Generated by update.nu; full object data is content-addressed outside Git.
import ../load-catalog.nix {
  url = "https://github.com/DzmingLi/battlenet.nix/releases/download/catalogs/dd7ba3c09d41b739b17a47c35f7b7d4d67b5a18e5ae8d86804badd4631ac8506.tar.gz";
  hash = "sha256-MdmRyoi6ka+1sYiW1VDMau/jmQ0DKCQkl4Zowr5gV9Q=";
  game = { "installation" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "architectures" = [ "arm64"
"x86_64" ]; "args" = [  ]; "executable" = "_classic_era_/World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "hash" = null; "runtime" = "native"; "storage" = { "completeInstallation" = true; "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-JQuLdJUrTGqwfeuItajhmDKz10EzNZ6h+uHjne6aEK8="; "key" = "26b68e5ddb5ae3011a84c41062da2efb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/26/b6/26b68e5ddb5ae3011a84c41062da2efb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; "schemaVersion" = 1; "storageFormat" = "casc-v7"; "tags" = [ "OSX"
"US"
"speech"
"text"
"esES"
"arm64" ]; "writerVersion" = 2; }; }; "installationDefaults" = { "application" = "World of Warcraft Classic.app"; "applicationPattern" = ""; "args" = [  ]; "executable" = "World of Warcraft Classic.app/Contents/MacOS/World of Warcraft Classic"; "runtime" = "native"; "storage" = { "dataDirectory" = "Data"; "installDirectory" = "_classic_era_"; "tags" = [ "OSX"
"US"
"speech"
"text"
"esES" ]; }; }; "locale" = "esES"; "platform" = "mac"; "productConfiguration" = { "hash" = "sha256-NxR4JVW3RlRif2kwZ18c5agUEbG7RjZ/c4eI7WffoV0="; "key" = "c9934edfc8f217a2e01c47e4deae8454"; "url" = "https://cdn.blizzard.com/tpr/configs/data/c9/93/c9934edfc8f217a2e01c47e4deae8454"; }; "release" = { "buildConfig" = { "hash" = "sha256-vx/+u+PJiGuGoFLVLDuGt2YA+kTzNQpKfdSpTKbHKLE="; "key" = "2417084b8b041ee120d02d4adf31b0bc"; "url" = "https://level3.ssl.blizzard.com/tpr/wow/config/24/17/2417084b8b041ee120d02d4adf31b0bc"; }; "buildId" = "70003"; "cdnConfig" = { "hash" = "sha256-JQuLdJUrTGqwfeuItajhmDKz10EzNZ6h+uHjne6aEK8="; "key" = "26b68e5ddb5ae3011a84c41062da2efb"; "url" = "https://cdn.blizzard.com/tpr/wow/config/26/b6/26b68e5ddb5ae3011a84c41062da2efb"; }; "cdnPath" = "tpr/wow"; "cdnServers" = [ "https://cdn.blizzard.com" ]; "keyRing" = ""; "product" = "wow_classic_era"; "productConfig" = "c9934edfc8f217a2e01c47e4deae8454"; "region" = "us"; "schemaVersion" = 1; "version" = "1.15.9.70003"; }; };
}