"""Deterministic CASC V7 storage writer. V8/client repair state is not synthesized.

See CascLib CascStructs.h, CascIndexFiles.cpp, CascReadFile.cpp. Each output
object has a locked SHA256 and verified encoded identity. Plaintext CKeys are
also checked when decoding is possible; encrypted resources are marked explicitly.
"""
import functools
import json
from pathlib import Path
import struct
import tempfile
import time
from urllib.parse import urlsplit

import tact
from ngdp import sri

MASK = 0xffffffff
SEGMENT_BITS = 30
SEGMENT_LIMIT = 1 << SEGMENT_BITS
SPAN_HEADER = 30
SEGMENT_HEADER = 480
# CASC's local span checksum mask (also documented in CascLib).
SPAN_MASK = (0x049396b8, 0x72a82a9b, 0xee626cca, 0x9917754f,
             0x15de40b1, 0xf5a8a9b6, 0x421eac7e, 0xa9d55c9a,
             0x317fd40c, 0x04faf80d, 0x3d6be971, 0x52933cfd,
             0x27f64b7d, 0xc6f5c11b, 0xd5757e3a, 0x6c388745)


def rotate(value, count):
    return ((value << count) | (value >> (32 - count))) & MASK


def lookup3(data, primary=0, secondary=0):
    """Bob Jenkins lookup3 hashlittle2; all arithmetic is unsigned 32-bit."""
    a = b = c = (0xdeadbeef + len(data) + primary) & MASK
    c = (c + secondary) & MASK
    offset = 0
    while len(data) - offset > 12:
        x, y, z = struct.unpack_from('<III', data, offset)
        a, b, c = (a + x) & MASK, (b + y) & MASK, (c + z) & MASK
        a = ((a - c) & MASK) ^ rotate(c, 4); c = (c + b) & MASK
        b = ((b - a) & MASK) ^ rotate(a, 6); a = (a + c) & MASK
        c = ((c - b) & MASK) ^ rotate(b, 8); b = (b + a) & MASK
        a = ((a - c) & MASK) ^ rotate(c, 16); c = (c + b) & MASK
        b = ((b - a) & MASK) ^ rotate(a, 19); a = (a + c) & MASK
        c = ((c - b) & MASK) ^ rotate(b, 4); b = (b + a) & MASK
        offset += 12
    tail = data[offset:]
    if not tail:
        return c, b
    padded = tail.ljust(12, b'\0')
    x, y, z = struct.unpack('<III', padded)
    a, b, c = (a + x) & MASK, (b + y) & MASK, (c + z) & MASK
    for target, source, count in (('c', 'b', 14), ('a', 'c', 11), ('b', 'a', 25),
                                   ('c', 'b', 16), ('a', 'c', 4), ('b', 'a', 14), ('c', 'b', 24)):
        values = {'a': a, 'b': b, 'c': c}
        value = ((values[target] ^ values[source]) - rotate(values[source], count)) & MASK
        if target == 'a': a = value
        elif target == 'b': b = value
        else: c = value
    return c, b


def bucket(ekey, seed=0, writer_version=1):
    value = functools.reduce(int.__xor__, bytes.fromhex(tact.key(ekey))[:9], 0)
    if writer_version >= 2:
        return ((value ^ (value >> 4)) + seed) & 15
    value ^= seed
    return (value ^ (value >> 4)) & 15


def span_header(ekey, size, global_offset, flags=0):
    if not SPAN_HEADER <= size <= SEGMENT_LIMIT:
        raise ValueError('invalid CASC local span size')
    data = bytes.fromhex(tact.key(ekey))[::-1] + struct.pack('<IH', size, flags)
    data += struct.pack('<I', lookup3(data, 0x3d6be971)[0])
    accum = bytearray(4)
    for index, value in enumerate(data):
        accum[index & 3] ^= value
    offset = (global_offset + SPAN_HEADER) & MASK
    mask = struct.pack('<I', SPAN_MASK[offset & 15] ^ offset)
    checksum = bytes(accum[(26 + j) & 3] ^ mask[(26 + j) & 3] for j in range(4))
    return data + checksum


def segment_header(segment, writer_version=1):
    # Reconstruction headers use a stable seed instead of the destination
    # directory; no timestamps or output/store path enters the generated bytes.
    result = bytearray()
    for wanted in range(16):
        seed = bytearray(bytes.fromhex(tact.md5(f'nix-casc-v7:{segment}:{wanted}'.encode())))
        for probe in range(256):
            seed[0] = probe
            if bucket(seed.hex(), 1, writer_version) == wanted:
                break
        result += span_header(seed.hex(), SPAN_HEADER, (segment << SEGMENT_BITS) + len(result),
                              flags=0 if writer_version >= 2 else 1)
    return bytes(result)


def index_file(number, entries, writer_version=1):
    """V7 guarded header, sorted section, and zeroed update pages."""
    # Contemporary client-storage IndexHeaderV2 uses little endian. The older
    # blizzget writer differs; neither byte order fixed the missing header maps.
    header = struct.pack('<H6BQ', 7, number, 0, 4, 5, 9, SEGMENT_BITS, SEGMENT_LIMIT)
    records = []
    for ekey, segment, offset, size in sorted(entries):
        if segment >= 1024 or offset >= SEGMENT_LIMIT or not 0 < size <= SEGMENT_LIMIT:
            raise ValueError('local index location out of range')
        records.append(bytes.fromhex(ekey)[:9] + ((segment << SEGMENT_BITS) | offset).to_bytes(5, 'big') + struct.pack('<I', size))
    pc = pb = 0
    for record in records:
        pc, pb = lookup3(record, pc, pb)
    body = b''.join(records)
    data = struct.pack('<II', len(header), lookup3(header)[0]) + header + bytes(8)
    data += struct.pack('<II', len(body), pc) + body
    # CascLib recognizes an empty V7 index through the zeroed update section.
    return data.ljust(max(0x30000, ((len(data) + 4095) // 4096) * 4096), b'\0')


def read_locked_object(descriptor, cache, download_missing=False):
    ekey = tact.key(descriptor['ekey'])
    path = Path(cache) / ekey
    raw = fetch_locked(descriptor) if download_missing and not path.exists() else path.read_bytes()
    if sri(raw) != descriptor['hash'] or len(raw) != descriptor['encodedSize']:
        raise ValueError('locked storage object encoded hash/size mismatch: ' + ekey)
    decoded = tact.storage_payload(raw, ekey, descriptor['ckey'], descriptor['decodedSize'])
    if decoded is None and not (descriptor.get('encrypted') is True and descriptor.get('decodedVerified') is False):
        raise ValueError('encrypted object must explicitly declare unverified plaintext')
    if decoded is not None and len(decoded) != descriptor['decodedSize']:
        raise ValueError('locked storage object decoded size mismatch: ' + ekey)
    return raw, decoded


def ordered_storage_objects(descriptors, cache, download_missing):
    """Bound network concurrency while retaining the deterministic write order."""
    ordered = iter(sorted(descriptors))
    if not download_missing:
        for ekey in ordered:
            yield ekey, read_locked_object(descriptors[ekey], cache)[0]
        return
    from collections import deque
    from concurrent.futures import ThreadPoolExecutor

    def fetch(ekey):
        return read_locked_object(descriptors[ekey], cache, True)[0]

    with ThreadPoolExecutor(max_workers=4) as pool:
        pending = deque()
        for _ in range(4):
            ekey = next(ordered, None)
            if ekey is not None:
                pending.append((ekey, pool.submit(fetch, ekey)))
        while pending:
            ekey, future = pending.popleft()
            yield ekey, future.result()
            following = next(ordered, None)
            if following is not None:
                pending.append((following, pool.submit(fetch, following)))


def build_info(lock, build_config):
    """Typed installation record; fields follow blizzget's installation writer.

    Empty timestamps keep the installation independent of build time. Install
    Key is the encoded key, unlike the first (content) key in build config.
    """
    release = lock['release']
    install = build_config.get('install', [])
    sizes = build_config.get('install-size', [])
    servers = release.get('cdnServers', [])
    hosts = list(dict.fromkeys(urlsplit(url).netloc for url in servers))
    fields = ['Branch!STRING:0', 'Active!DEC:1', 'Build Key!HEX:16', 'CDN Key!HEX:16',
              'Install Key!HEX:16', 'IM Size!DEC:4', 'CDN Path!STRING:0',
              'CDN Hosts!STRING:0', 'CDN Servers!STRING:0', 'Tags!STRING:0',
              'Armadillo!STRING:0', 'Last Activated!STRING:0', 'Version!STRING:0',
              'Keyring!HEX:16', 'Product!STRING:0', 'BGDL Key!HEX:16']
    row = [release['region'], '1', release['buildConfig']['key'], release['cdnConfig']['key'],
           install[1] if len(install) > 1 else '', sizes[0] if sizes else '',
           release['cdnPath'], ' '.join(hosts), ' '.join(servers),
           ' '.join(lock.get('tags', [])), '', '', release['version'],
           release.get('keyRing', ''), release['product'], '']
    if any('\n' in value or '\r' in value or '|' in value for value in row):
        raise ValueError('unsafe build.info field')
    return '|'.join(fields) + '\n' + '|'.join(row) + '\n'


def validate_closure(lock, cache):
    """Prove completeness against locked official manifests, not a boolean."""
    if not lock.get('completeInstallation', False):
        return
    bootstrap = lock.get('bootstrap')
    if not bootstrap or bootstrap['release'] != lock['release']:
        raise ValueError('full installation validation requires matching bootstrap manifests')
    plan = tact.make_plan(bootstrap, cache, lock['tags'])
    objects = {item['ekey']: item for item in lock['objects']}
    for item in plan['downloadObjects']:
        if item['ekey'] not in objects or objects[item['ekey']]['encodedSize'] != item['size']:
            raise ValueError('full installation validation: missing download object ' + item['ekey'])
    files = {item['path']: item for item in lock['installFiles']}
    if len(files) != len(lock['installFiles']) or set(files) != {item['path'] for item in plan['installFiles']}:
        raise ValueError('full installation validation: install manifest paths differ')
    for expected in plan['installFiles']:
        actual = files[expected['path']]
        if actual['ckey'] != expected['ckey'] or actual['size'] != expected['size'] or actual['ekey'] not in expected['ekeys']:
            raise ValueError('full installation validation: install file identity differs')
    configs = {}
    for name in ('buildConfig', 'cdnConfig'):
        descriptor = lock['release'][name]
        raw = (Path(cache) / (descriptor['key'] + '.config')).read_bytes()
        if tact.md5(raw) != descriptor['key'] or sri(raw) != descriptor['hash']:
            raise ValueError('full installation validation: config identity differs')
        configs[name] = tact.config(raw)
    ckeys = {item['ckey'] for item in objects.values()}
    for name, values in configs['buildConfig'].items():
        if name == 'root' or name == 'vfs-root' or __import__('re').fullmatch(r'vfs-\d+', name):
            if values[0] not in ckeys:
                raise ValueError('full installation validation: missing root/VFS object')
    for descriptor in bootstrap['objects'].values():
        if objects.get(descriptor['ekey'], {}).get('hash') != descriptor['hash']:
            raise ValueError('full installation validation: missing bootstrap object')


def write_storage(lock, cache, output, segment_limit=SEGMENT_LIMIT, download_missing=False):
    if lock['schemaVersion'] != 1 or lock['storageFormat'] != 'casc-v7':
        raise ValueError('unsupported storage lock format')
    if lock.get('writerVersion', 1) not in (1, 2):
        raise ValueError('unsupported storage writer version')
    validate_closure(lock, cache)
    if not SEGMENT_HEADER < segment_limit <= SEGMENT_LIMIT:
        raise ValueError('invalid data segment limit')
    root = Path(output)
    if root.exists():
        raise ValueError('storage output already exists; refusing to merge with old files')
    root.parent.mkdir(parents=True, exist_ok=True)
    install_directory = lock.get('installDirectory', '')
    if install_directory:
        install_directory = tact.safe_path(install_directory)
    # Publish only after the entire tree has passed integrity and path checks.
    with tempfile.TemporaryDirectory(dir=root.parent, prefix='.' + root.name + '-') as temporary:
        tree = Path(temporary) / 'tree'
        tree.mkdir()
        data_dir = tree / tact.safe_path(lock['dataDirectory'])
        data = data_dir / 'data'
        data.mkdir(parents=True)
        entries = {i: [] for i in range(16)}
        descriptors = {}
        prefixes = set()
        for descriptor in lock['objects']:
            ekey = tact.key(descriptor['ekey'])
            if ekey in descriptors or ekey[:18] in prefixes:
                raise ValueError('duplicate EKey or truncated 9-byte EKey collision')
            descriptors[ekey] = descriptor
            prefixes.add(ekey[:18])
        segment = 0
        stream = None
        try:
            import time
            started = last_report = time.monotonic()
            written = completed = 0
            for ekey, raw in ordered_storage_objects(descriptors, cache, download_missing):
                size = SPAN_HEADER + len(raw)
                if size + SEGMENT_HEADER > segment_limit:
                    raise ValueError('object cannot fit in one local data segment')
                if stream is None or stream.tell() + size > segment_limit:
                    if stream is not None:
                        stream.close()
                        segment += 1
                    if segment >= 1024:
                        raise ValueError('too many CASC data segments')
                    stream = (data / f'data.{segment:03d}').open('wb')
                    header = segment_header(segment, lock.get('writerVersion', 1))
                    stream.write(header)
                    if lock.get('writerVersion', 1) >= 2:
                        # Client validation queries reconstruction keys with
                        # seed 1, unlike ordinary object lookups (seed 0).
                        for header_offset in range(0, SEGMENT_HEADER, SPAN_HEADER):
                            header_key = header[header_offset:header_offset + 16][::-1].hex()
                            entries[bucket(header_key, 1, 2)].append(
                                (header_key, segment, header_offset, SPAN_HEADER))
                offset = stream.tell()
                stream.write(span_header(ekey, size, (segment << SEGMENT_BITS) + offset))
                stream.write(raw)
                entries[bucket(ekey)].append((ekey, segment, offset, size))
                written += len(raw)
                completed += 1
                if download_missing and time.monotonic() - last_report >= 10:
                    elapsed = time.monotonic() - started
                    print(f'Storage: {completed}/{len(descriptors)} objects, {written / 2**30:.2f} GiB, {written / elapsed / 2**20:.1f} MiB/s', flush=True)
                    last_report = time.monotonic()
        finally:
            if stream is not None:
                stream.close()
        for number, items in entries.items():
            (data / f'{number:02x}00000001.idx').write_bytes(index_file(number, items, lock.get('writerVersion', 1)))
        if lock.get('writerVersion', 1) >= 2:
            # Official clients initialize the streaming resolver even with all
            # selected payloads resident. Supply the already locked CDN indexes.
            for descriptor in lock.get('bootstrap', {}).get('archives', []):
                archive = tact.key(descriptor['archive'])
                path = Path(cache) / (archive + '.index')
                raw = tact.bounded_get(descriptor['url'], descriptor['size']) if download_missing and not path.exists() else path.read_bytes()
                if len(raw) != descriptor['size'] or sri(raw) != descriptor['hash']:
                    raise ValueError('locked CDN index hash/size mismatch')
                tact.archive_index(raw, archive)
                target = data_dir / 'indices' / (archive + '.index')
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(raw)
        reserved = {p.relative_to(tree).as_posix().casefold() for p in tree.rglob('*')}
        reserved.update({'.build.info', '.nix-casc.json'})
        data_path = data_dir.relative_to(tree).as_posix().casefold()
        protected = [data_path + '/' + part for part in ('data', 'config', 'indices')]
        # Ordinary files come from the locked install manifest, not user paths.
        for file in lock.get('installFiles', []):
            path = tact.safe_path(file['path'])
            if install_directory:
                path = install_directory + '/' + path
            folded = path.casefold()
            if folded in reserved or any(folded == area or folded.startswith(area + '/') or area.startswith(folded + '/') for area in protected):
                raise ValueError('installation file overlaps CASC metadata: ' + path)
            ekey = file['ekey']
            if ekey not in descriptors:
                raise ValueError('install file references an absent locked object')
            descriptor = descriptors[ekey]
            if file['ckey'] != descriptor['ckey'] or file['size'] != descriptor['decodedSize']:
                raise ValueError('install file identity mismatch')
            _, decoded = read_locked_object(descriptor, cache, download_missing)
            if decoded is None:
                raise ValueError('ordinary install file needs plaintext: ' + path)
            target = tree / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(decoded)
            if 'OSX' in lock.get('tags', []) and (
                    decoded[:4] in (b'\xcf\xfa\xed\xfe', b'\xfe\xed\xfa\xcf',
                                    b'\xce\xfa\xed\xfe', b'\xfe\xed\xfa\xce',
                                    b'\xca\xfe\xba\xbe', b'\xbe\xba\xfe\xca',
                                    b'\xca\xfe\xba\xbf', b'\xbf\xba\xfe\xca')
                    or decoded.startswith(b'#!')):
                target.chmod(0o755)
            reserved.add(path.casefold())
        release = lock['release']
        for name in ('buildConfig', 'cdnConfig'):
            descriptor = release[name]
            key = tact.key(descriptor['key'])
            content = (Path(cache) / (key + '.config')).read_bytes()
            if tact.md5(content) != key or sri(content) != descriptor['hash']:
                raise ValueError('locked local config mismatch')
            path = data_dir / 'config' / key[:2] / key[2:4] / key
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        if lock.get('writerVersion', 1) >= 2:
            config = tact.config((Path(cache) / (release['buildConfig']['key'] + '.config')).read_bytes())
            info = build_info(lock, config)
        else:
            # Preserve the NAR of existing locked snapshots. Version 1 is a
            # reader-validated laboratory format, not a playable client proof.
            fields = ['Branch!STRING:0', 'Active!DEC:1', 'Build Key!HEX:16', 'CDN Key!HEX:16',
                      'CDN Path!STRING:0', 'CDN Hosts!STRING:0', 'Tags!STRING:0', 'Version!STRING:0', 'Product!STRING:0']
            row = [release['region'], '1', release['buildConfig']['key'], release['cdnConfig']['key'],
                   release['cdnPath'], '', ' '.join(lock.get('tags', [])), release['version'], release['product']]
            if any('\n' in value or '\r' in value or '|' in value for value in row):
                raise ValueError('unsafe build.info field')
            info = '|'.join(fields) + '\n' + '|'.join(row) + '\n'
        (tree / '.build.info').write_text(info)
        # A partial laboratory store must never be presented as a full install.
        (tree / '.nix-casc.json').write_text(json.dumps({'schemaVersion': 1,
            'completeInstallation': lock.get('completeInstallation', False),
            'storageFormat': 'casc-v7', 'objectCount': len(descriptors)}, sort_keys=True) + '\n')
        tree.rename(root)


def fetch_locked(descriptor):
    source = descriptor['source']
    raw = tact.bounded_get(source['url'], descriptor['encodedSize'], source.get('offset'), descriptor['encodedSize'])
    if sri(raw) != descriptor['hash']:
        raise ValueError('storage download encoded SHA256 mismatch')
    decoded = tact.storage_payload(raw, descriptor['ekey'], descriptor['ckey'], descriptor['decodedSize'])
    if decoded is None and not (descriptor.get('encrypted') is True and descriptor.get('decodedVerified') is False):
        raise ValueError('encrypted object must explicitly declare unverified plaintext')
    if decoded is not None and len(decoded) != descriptor['decodedSize']:
        raise ValueError('storage download decoded size mismatch')
    return raw


def materialize_installation(lock, output, cache=None):
    """Use a verified complete cache, or stream resources for large CI jobs."""
    if not lock.get('completeInstallation'):
        raise ValueError('mkInstallation requires a complete closure lock')
    if cache is not None:
        write_storage(lock, cache, output)
        return
    with tempfile.TemporaryDirectory(prefix='battlenet-bootstrap-') as cache:
        for name in ('buildConfig', 'cdnConfig'):
            descriptor = lock['release'][name]
            tact.atomic_bytes(Path(cache) / (descriptor['key'] + '.config'), tact.read_config(descriptor))
        for descriptor in lock['bootstrap']['objects'].values():
            raw = fetch_locked(dict(descriptor, source={'url': descriptor['url']}))
            tact.atomic_bytes(Path(cache) / descriptor['ekey'], raw)
        write_storage(lock, cache, output, download_missing=True)


def prepare_sample(bootstrap, cache, names, paths, data_directory='Data', max_bytes=64 * 1024 * 1024):
    """Lock all root/VFS metadata plus explicit ordinary files, never game assets."""
    from concurrent.futures import ThreadPoolExecutor
    plan = tact.resolve_plan(bootstrap, cache, names)
    files = {e['path']: e for e in plan['installFiles']}
    chosen = []
    for path in paths:
        path = tact.safe_path(path)
        if path not in files:
            raise ValueError('sample file is not a selected install entry: ' + path)
        chosen.append(files[path])
    release = bootstrap['release']
    configs = {}
    for name in ('buildConfig', 'cdnConfig'):
        data = tact.read_config(release[name])
        tact.atomic_bytes(Path(cache) / (release[name]['key'] + '.config'), data)
        configs[name] = data
    build = tact.config(configs['buildConfig'])
    references = {name: value for name, value in build.items()
                  if name == 'root' or name == 'vfs-root' or __import__('re').fullmatch(r'vfs-\d+', name)}
    manifest_data = tact.load_manifests(bootstrap, cache)
    needed_ckeys = {tact.key(values[0]) for values in references.values()}
    lookup = tact.encoding(manifest_data['encoding'], needed_ckeys)
    locations = {}
    for descriptor in bootstrap['archives']:
        raw = (Path(cache) / (descriptor['archive'] + '.index')).read_bytes()
        if sri(raw) != descriptor['hash']:
            raise ValueError('sample index SHA256 mismatch')
        for ekey, location in tact.archive_index(raw, descriptor['archive']).items():
            locations.setdefault(ekey, location)
    pending = {}
    for name, values in references.items():
        ckey = tact.key(values[0])
        mapping = lookup.get(ckey)
        if mapping is None:
            raise ValueError('root/VFS CKey missing from encoding: ' + name)
        candidates = [tact.key(values[1])] if len(values) == 2 else mapping['ekeys']
        ekey = next((e for e in candidates if e in locations), None)
        if ekey is None:
            raise ValueError('root/VFS object absent from locked indexes: ' + name)
        pending[ekey] = {'ekey': ekey, 'ckey': ckey, 'decodedSize': mapping['size'],
                         'location': locations[ekey]}
    for file in chosen:
        pending[file['ekey']] = {'ekey': file['ekey'], 'ckey': file['ckey'],
                                'decodedSize': file['size'], 'location': file['location']}
    if sum(e['location']['size'] for e in pending.values()) > max_bytes:
        raise ValueError(f'sample would exceed {max_bytes // 2**20} MiB; select smaller explicit files')

    def prefetch(item):
        ekey, ckey, location = item['ekey'], item['ckey'], item['location']
        object_key = location.get('archive', ekey)
        errors = []
        for server in release['cdnServers']:
            url = f'{server.rstrip("/")}/{release["cdnPath"]}/data/{object_key[:2]}/{object_key[2:4]}/{object_key}'
            try:
                path = Path(cache) / ekey
                raw = path.read_bytes() if path.exists() else tact.bounded_get(url, location['size'], location.get('offset'), location['size'])
                decoded = tact.storage_payload(raw, ekey, ckey, item['decodedSize'])
                if len(raw) != location['size'] or (decoded is not None and len(decoded) != item['decodedSize']):
                    raise ValueError('sample object size mismatch')
                tact.atomic_bytes(path, raw)
                return {'ekey': ekey, 'ckey': ckey, 'encodedSize': len(raw), 'decodedSize': item['decodedSize'],
                        'hash': sri(raw), 'source': dict(location, url=url, kind='archive' if 'archive' in location else 'loose'),
                        **({'encrypted': True, 'decodedVerified': False} if decoded is None else {})}
            except (OSError, ValueError) as error:
                errors.append(str(error))
        raise ValueError(ekey + ': ' + '; '.join(errors))

    with ThreadPoolExecutor(max_workers=6) as executor:
        objects = list(executor.map(prefetch, [pending[k] for k in sorted(pending)]))
    by_key = {e['ekey']: e for e in objects}
    for descriptor in bootstrap['objects'].values():
        by_key[descriptor['ekey']] = dict(descriptor, source={'kind': 'loose', 'url': descriptor['url']})
    return {'schemaVersion': 1, 'storageFormat': 'casc-v7', 'completeInstallation': False,
            'dataDirectory': tact.safe_path(data_directory), 'release': release, 'tags': names,
            'objects': [by_key[k] for k in sorted(by_key)],
            'installFiles': [{'path': e['path'], 'ckey': e['ckey'], 'ekey': e['ekey'], 'size': e['size']} for e in chosen]}
